import { useEffect, useMemo, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { marked } from 'marked';
import { api } from '../lib/api';
import { ArrowLeft, Printer, BookOpen } from 'lucide-react';

/**
 * Formatted paper view for a deep-research report: title block, abstract
 * (TL;DR), body with numbered sections and figures, and an auto-generated
 * References section mapped from the [S#] citations to the run's sources.
 * Print-optimized — Ctrl-P produces a clean PDF.
 */

const md = (s: string) => ({ __html: marked.parse(s ?? '', { async: false }) as string });

export default function PaperView() {
  const { spaceId, runId } = useParams();
  const [run, setRun] = useState<any>(null);

  useEffect(() => {
    if (!runId) return;
    api.get(`/research/${runId}`).then((r) => setRun(r.run)).catch(() => {});
  }, [runId]);

  const paper = useMemo(() => buildPaper(run), [run]);

  if (!run) return <div className="p-8 text-set-dim">Loading paper…</div>;
  if (!run.report_md) return (
    <div className="p-8 text-set-dim">
      No report yet — <Link className="underline" to={`/app/space/${spaceId}/research/${runId}`}>view the run</Link>.
    </div>
  );

  return (
    <div className="paper-shell min-h-full bg-set-bg">
      {/* Screen chrome (hidden on print) */}
      <div className="print:hidden sticky top-0 z-10 bg-set-panel/95 backdrop-blur border-b border-set-border">
        <div className="max-w-3xl mx-auto px-4 py-2.5 flex items-center gap-3">
          <Link to={`/app/space/${spaceId}/research/${runId}`} className="set-btn-ghost text-xs flex items-center gap-1">
            <ArrowLeft size={13} /> Run
          </Link>
          <span className="set-mono set-mono-dim flex-1 truncate">
            {paper.wordCount} words · {run.source_count} sources · {run.style}
          </span>
          <button className="set-btn text-xs flex items-center gap-1" onClick={() => window.print()}>
            <Printer size={12} /> PDF
          </button>
        </div>
      </div>

      <article className="paper-body max-w-3xl mx-auto px-6 py-10 sm:py-14">
        {/* Title block */}
        <header className="border-b border-set-border pb-6 mb-8">
          <div className="set-mono set-mono-dim mb-3">
            SET Deep Research · {new Date(run.created_at).toLocaleDateString()} · {paper.duration}
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-white leading-tight tracking-tight">
            {paper.title}
          </h1>
          <p className="mt-3 text-sm text-set-dim leading-relaxed italic">{run.question}</p>
        </header>

        {/* Abstract */}
        {paper.abstract && (
          <section className="mb-8">
            <div className="set-mono set-mono-dim mb-2">Abstract</div>
            <div className="text-sm text-set-text/90 leading-relaxed border-l-2 border-set-accent/50 pl-4" dangerouslySetInnerHTML={{ __html: paper.abstract }} />
          </section>
        )}

        {/* Body */}
        <div className="paper-prose" dangerouslySetInnerHTML={{ __html: paper.body }} />

        {/* References */}
        {paper.references.length > 0 && (
          <section className="mt-10 pt-6 border-t border-set-border">
            <div className="set-mono set-mono-dim mb-3">References</div>
            <ol className="space-y-1.5">
              {paper.references.map((ref: any, i: number) => (
                <li key={i} className="text-xs text-set-dim leading-relaxed flex gap-2">
                  <span className="set-mono-num text-set-accent/80 shrink-0">[{i + 1}]</span>
                  <span className="min-w-0">
                    <a href={ref.uri ?? '#'} target="_blank" rel="noreferrer" className="text-set-text/80 hover:text-set-accent break-all">
                      {ref.name || ref.uri}
                    </a>
                  </span>
                </li>
              ))}
            </ol>
          </section>
        )}

        <footer className="mt-10 pt-4 border-t border-set-border/60 text-[10px] text-set-dim/60 set-mono">
          Generated by SET deep research · {run.source_count} sources · {run.style} style · {paper.wordCount} words
        </footer>
      </article>
    </div>
  );
}

/** Split report_md into title / abstract / body, remap [S#] to numbered refs. */
function buildPaper(run: any) {
  const mdText: string = run.report_md ?? '';
  const lines = mdText.split('\n');

  // title from first h1
  let title = run.question?.slice(0, 120) ?? 'Research report';
  for (const l of lines) {
    const m = l.match(/^#\s+(.+)$/);
    if (m) { title = m[1]; break; }
  }

  // abstract = TL;DR section (up to next ## heading)
  let abstract = '';
  const tldrIdx = lines.findIndex((l) => /^##?\s*(TL;DR|Abstract)/i.test(l));
  if (tldrIdx >= 0) {
    const buf: string[] = [];
    for (let i = tldrIdx + 1; i < lines.length; i++) {
      if (/^##\s/.test(lines[i])) break;
      buf.push(lines[i]);
    }
    abstract = buf.join('\n').trim();
  }

  // references: map [S#] indices to the run's sources in order
  const sources = (run.sources ?? []).filter(Boolean);
  const used = new Set<number>();
  const bodyMd = mdText.replace(/\[S(\d+)\]/g, (_m, n) => {
    const idx = parseInt(n, 10) - 1;
    if (idx >= 0 && idx < sources.length) {
      used.add(idx);
      return `<sup class="cite">[${idx + 1}]</sup>`;
    }
    return '';
  });

  // strip the TL;DR block from body (it's the abstract now)
  let body = bodyMd;
  if (tldrIdx >= 0) {
    const before = lines.slice(0, tldrIdx);
    let end = lines.length;
    for (let i = tldrIdx + 1; i < lines.length; i++) {
      if (/^##\s/.test(lines[i])) { end = i; break; }
    }
    body = [...before, ...lines.slice(end)].join('\n').replace(/^#\s+.+$/m, '').trim();
    // re-apply citation remap for this path
    body = body.replace(/\[S(\d+)\]/g, (_m, n) => {
      const idx = parseInt(n, 10) - 1;
      return idx >= 0 && idx < sources.length ? `<sup class="cite">[${idx + 1}]</sup>` : '';
    });
  }

  // references list: sources actually cited (or all, if few)
  const refIdxs = used.size > 0 ? [...used].sort((a, b) => a - b) : sources.map((_: any, i: number) => i);
  const references = refIdxs.map((i: number) => sources[i]).filter(Boolean);

  const wordCount = mdText.split(/\s+/).filter(Boolean).length;
  const mins = run.progress?.pages_budget ? `${run.progress.pages_visited ?? 0} pages read` : '';

  return {
    title,
    abstract: abstract ? String(marked.parse(abstract, { async: false })) : '',
    body: String(marked.parse(body, { async: false })),
    references,
    wordCount,
    duration: mins,
  };
}
